### ISSUE TITLE
Is It possible to run this on Linux?

### ISSUE THREAD

**Issue by xcom169** [13xforever/vkdiag#2]
Hello All,

Is It possible to run this on Linux?

Thanks

**Comment by 13xforever** [comment]
No, every OS has very different driver and layer registration/discovery mechanisms, this is Windows-specific diagnostics as it had the most changes over time with more convoluted requirements.

You can use [Archwiki](https://wiki.archlinux.org/title/Vulkan) to check and verify your vulkan setup regardless your distro.
