### ISSUE TITLE
vulkan diagnostic tool log

### ISSUE THREAD

**Issue by Karrar777** [13xforever/vkdiag#5]
[+] VkDiag version: 1.3.5
[i] CPU: 12th Gen Intel(R) Core(TM) i3-12100
[+] OS: ‏‏Microsoft Windows 11 Pro
[+] Version: 10.0.22631 (Windows 11 23H2)
[+] System Vulkan loader version: 1.3.261.1
​
Found 2 active GPUs:
[+] LuminonCore IDDCX Adapter
    [+] Driver version: 1.0.2018.1204 (12-4-2018)
    [!] Please consider updating your video driver
[v] Intel(R) UHD Graphics 730
    [+] Driver version: 31.0.101.5592 (6-19-2024)
    [v] Proper Vulkan driver registration
​
Vulkan registration information:
[+] No explicit driver registration entries
[+] Implicit layers registration (HKEY_LOCAL_MACHINE, 64-bit):
    [+] Vulkan overlay layer for Epic Online Services, API v1.2.136 (EOSOverlayVkLayer-Win64.json)
    [+] Twitch Game Capture and Overlay Rendering, API v1.1.0 (TwitchOverlayVulkanConfig64.json)
    [+] RTSS overlay hook bootstrap, API v1.1.73 (RTSSVkLayer64.json)
    [ ] Overwolf Overlay, v2.2.254.0, API v1.2.131 (ow-vulkan-overlay64.json)
    [+] OWOBS hook, v2.2.250.1, API v1.2.131 (ow-graphics-vulkan64.json)
    [+] Steam Overlay, API v1.3.207 (SteamOverlayVulkanLayer64.json)
    [+] Steam Pipeline Caching, API v1.3.207 (SteamFossilizeVulkanLayer64.json)
[+] Implicit layers registration (HKEY_LOCAL_MACHINE, 32-bit):
    [+] Vulkan overlay layer for Epic Online Services, API v1.2.136 (EOSOverlayVkLayer-Win32.json)
    [+] Twitch Game Capture and Overlay Rendering, API v1.1.0 (TwitchOverlayVulkanConfig32.json)
    [+] RTSS overlay hook bootstrap, API v1.1.73 (RTSSVkLayer32.json)
    [+] Steam Overlay, API v1.3.207 (SteamOverlayVulkanLayer.json)
    [+] Steam Pipeline Caching, API v1.3.207 (SteamFossilizeVulkanLayer.json)
[!] Explicit layers registration (HKEY_LOCAL_MACHINE, 64-bit):
    [x] SocialClubVulkanLayer.json
    [+] LunarG API dump, API v1.3.283 (VkLayer_api_dump.json)
    [+] GFXReconstruct Capture Layer Version 1.0.4, API v1.3.283 (VkLayer_gfxreconstruct.json)
    [+] Khronos Synchronization2, API v1.3.283 (VkLayer_khronos_synchronization2.json)
    [+] Khronos Validation, API v1.3.283 (VkLayer_khronos_validation.json)
    [+] Execution Monitoring, API v1.3.283 (VkLayer_monitor.json)
    [+] LunarG image capture, API v1.3.283 (VkLayer_screenshot.json)
    [+] Khronos Profiles, API v1.3.283 (VkLayer_khronos_profiles.json)
    [+] Khronos Shader object, API v1.3.283 (VkLayer_khronos_shader_object.json)
[!] Explicit layers registration (HKEY_LOCAL_MACHINE, 32-bit):
    [x] SocialClubVulkanLayer.json
[+] Implicit layers registration (HKEY_CURRENT_USER, 64-bit):
    [+] Vulkan overlay layer for Epic Online Services, API v1.2.136 (EOSOverlayVkLayer-Win32.json)
    [+] Vulkan overlay layer for Epic Online Services, API v1.2.136 (EOSOverlayVkLayer-Win64.json)
    [+] LunarG Override, API v1.3.283 (VkLayer_override.json)
[+] No 64-bit explicit layers registered in HKEY_CURRENT_USER
​
Remember to screenshot or copy this screen content for support.

**Comment by 13xforever** [comment]
idk what's going on here, but you are obviously confused. Please do not open extraneous issues, thank you.
