### ISSUE TITLE
i need help with the emulator RPCS3

### ISSUE THREAD

**Issue by babizinha90** [13xforever/vkdiag#6]
So when I try to download the emulator after extracting it, this message appears on my screen and I can't install the emulator. Please help me!

![c6298b13-1d43-4e29-b9e8-1e17b4bccdb6](https://github.com/user-attachments/assets/8a617d8c-4760-40e1-b5bd-b3f29020d583)

**Comment by 13xforever** [comment]
ask the rpcs3 on their [discord or forums](https://rpcs3.net/)? you will not get any support with different project here
